### ISSUE TITLE
Problems in analysis

### ISSUE THREAD

**Issue by versi-color** [microDM/MicFunPred#11]
Hi again!

I keep getting this error and I am not sure how to proceed:

Traceback (most recent call last):
  File "/usr/local/bin/MicFunPred_run_pipeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('MicFunPred==1.0.0', 'MicFunPred_run_pipeline.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyarrow' distribution was not found and is required by MicFunPred

Thank you!

**Comment by microDM** [comment]
Please install pyarrow first. 
```
pip install pyarrow
```
