### ISSUE TITLE
error while running MicFunPred

### ISSUE THREAD

**Issue by anitatiknaik** [microDM/MicFunPred#12]
Running BLAST with 98.3 cut-off.
Traceback (most recent call last):
  File "/usr/local/bin/MicFunPred_run_pipeline.py", line 102, in <module>
    fp.blast(os.path.join(os.getcwd(),in_repSet), blastDbPath, in_numCores, cwd)
  File "/usr/local/lib/python2.7/site-packages/micfunpreDefinitions/micfunpreDefinitions.py", line 41, in blast
    subBlast = subprocess.Popen(cmd,stdin=subprocess.PIPE,stderr=subprocess.PIPE,shell=True)
UnboundLocalError: local variable 'cmd' referenced before assignment

**Comment by microDM** [comment]
Can you try now? Which system you are using?
